# Generated by Django 4.1 on 2022-09-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0002_alter_useraddress_options_useraddress_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='name',
            field=models.CharField(max_length=256, verbose_name='you name'),
        ),
    ]
