# Generated by Django 4.1 on 2022-09-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='email',
            field=models.CharField(default='1', max_length=140),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='mobile',
            field=models.CharField(default='1', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Out for shipping', 'Out for shipping'), ('Order Placed', 'Order placed')], default='Pending', max_length=150),
        ),
    ]
