# Generated by Django 4.1 on 2022-09-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0013_alter_order_status_alter_orderitem_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for shipping', 'Out for shipping'), ('Completed', 'Completed'), ('Order Placed', 'Order placed')], default='Order placed', max_length=150),
        ),
    ]
