# Generated by Django 4.1 on 2022-09-20 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_wishlist'),
        ('accountmanage', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order placed'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Out for shipping', 'Out for shipping')], default='Order placed', max_length=150),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcount', to='products.product'),
        ),
    ]
