# Generated by Django 4.1 on 2022-09-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0015_alter_order_status_alter_orderitem_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Placed', 'Order placed'), ('Completed', 'Completed'), ('Out for shipping', 'Out for shipping')], default='Order placed', max_length=150),
        ),
    ]
