# Generated by Django 4.1 on 2022-09-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Order Placed', 'Order placed'), ('Out for shipping', 'Out for shipping')], default='Order placed', max_length=150),
        ),
    ]
