# Generated by Django 4.1 on 2022-09-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Out for shipping', 'Out for shipping'), ('Order Placed', 'Order placed')], default='Order placed', max_length=150),
        ),
    ]
