# Generated by Django 4.1 on 2022-09-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for shipping', 'Out for shipping'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Order Placed', 'Order placed')], default='Order placed', max_length=150),
        ),
    ]
