# Generated by Django 4.1 on 2022-09-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0021_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order placed'), ('Out for shipping', 'Out for shipping'), ('Completed', 'Completed'), ('Out for Delivery', 'Out for Delivery')], default='Order placed', max_length=150),
        ),
    ]
