# Generated by Django 4.1 on 2022-09-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for Delivery', 'Out for Delivery'), ('Completed', 'Completed'), ('Shipped', 'Shipped'), ('Order Placed', 'Order placed')], default='Order placed', max_length=150),
        ),
    ]
