# Generated by Django 4.1 on 2022-09-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0025_alter_order_message_alter_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Shipped', 'Shipped'), ('Completed', 'Completed')], default='Order confirmed', max_length=150),
        ),
    ]
