# Generated by Django 4.1 on 2022-09-30 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountmanage', '0027_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Shipped', 'Shipped'), ('Order confirmed', 'Order confirmed'), ('Order cancelled', 'Order cancelled'), ('Out for Delivery', 'Out for Delivery'), ('Completed', 'Completed')], default='Order confirmed', max_length=150),
        ),
        migrations.CreateModel(
            name='userpic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_image', models.FileField(upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
