# Generated by Django 4.1 on 2022-09-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0029_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Order confirmed', 'Order confirmed'), ('Returned', 'Returned'), ('Shipped', 'Shipped'), ('Order cancelled', 'Order cancelled'), ('Out for Delivery', 'Out for Delivery')], default='Order confirmed', max_length=150),
        ),
    ]
