# Generated by Django 4.1 on 2022-10-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0035_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order cancelled', 'Order cancelled'), ('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Completed', 'Completed'), ('Returned', 'Returned')], default='Order confirmed', max_length=150),
        ),
    ]
