# Generated by Django 4.1 on 2022-10-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0036_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Order confirmed', 'Order confirmed'), ('Completed', 'Completed'), ('Order cancelled', 'Order cancelled'), ('Returned', 'Returned'), ('Out for Delivery', 'Out for Delivery')], default='Order confirmed', max_length=150),
        ),
    ]
