# Generated by Django 4.1 on 2022-10-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanage', '0040_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Order cancelled', 'Order cancelled'), ('Returned', 'Returned'), ('Out for Delivery', 'Out for Delivery'), ('Shipped', 'Shipped'), ('Completed', 'Completed')], default='Order confirmed', max_length=150),
        ),
    ]
