# Generated by Django 4.1 on 2022-08-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_2',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_3',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
