# Generated by Django 4.1 on 2022-08-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories_id',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='products.categories'),
        ),
        migrations.CreateModel(
            name='Cartmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
