# Generated by Django 4.1 on 2022-08-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_categories_id_cartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='categories',
            name='url_slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
