# Generated by Django 4.1 on 2022-09-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_categories_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories'),
        ),
    ]
