# Generated by Django 4.1 on 2022-09-03 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_subcategory_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='url_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='url_slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_title', models.TextField(max_length=255)),
                ('spec_description', models.TextField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
