# Generated by Django 4.1 on 2022-09-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_categories_url_slug_alter_subcategory_url_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='url_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
