# Generated by Django 4.1 on 2022-09-04 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_url_slug_alter_subcategory_url_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_details', to='products.product'),
        ),
    ]
