# Generated by Django 4.1 on 2022-09-11 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='cart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.cart'),
        ),
    ]
