# Generated by Django 4.1 on 2022-09-11 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_discount_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='cart_id',
        ),
    ]
