# Generated by Django 4.1 on 2022-09-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_newcart_newcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
