# Generated by Django 4.1 on 2022-10-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='test',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
