# Generated by Django 4.1 on 2022-10-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_coupon_test_coupon_tester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='tester',
        ),
    ]
