# Generated by Django 4.1 on 2022-10-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_couponuser_coupon_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponuser',
            name='coupon_modal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.coupon'),
        ),
    ]
